spring.application.name=Backend-servicehub
spring.datasource.url=jdbc:mysql://localhost:3306/servicehub
spring.datasource.username=root
spring.datasource.password=Saroj@77900

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
